version: '3'
services:
  db:
    container_name: open_nlp_db
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: quotes
      MYSQL_ROOT_PASSWORD: secret123
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always
  app:
    build: .
    container_name: open_nlp_app_container
    image: open_nlp_app:latest
    # volumes:
      # - ./:/etc/app
    ports:
      - "8080:8080"
    depends_on:
      - db